### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Denys-Shapovalenko** [Denys-Shapovalenko/homepage#6]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by whaplzzz** [comment]
**Кино**
Дональд Трамп известен комично сыгранными ролями самого себя в телесериалах и художественных фильмах, таких как «Один дома 2: Потерянный в Нью-Йорке», «Няня», «Принц из Беверли-Хиллз», «Дни нашей жизни», «Любовь с уведомлением», и ролью характерного героя в фильме «Шалопаи». Его нередко изображают как комедийные актёры, так и артисты других жанров. Трамп также участвует в различных ток-шоу и других телевизионных программах.

По заявлению сценариста фильма «Назад в будущее» Боба Гейла, Дональд Трамп является прототипом Биффа Таннена из фильма «Назад в будущее 2», когда Марти Макфлай попал в «альтернативный» 1985 год. В свою очередь, актёр, игравший Биффа (Том Уилсон), утверждает, что между его героем и Трампом нет ничего общего.

**Музыка**

В 2013 году снялся в музыкальном клипе «In Another Life» российского певца азербайджанского происхождения Эмина Агаларова. 

**СМИ**

В 2000 году в 17-й серии 11 сезона мультсериала «Симпсоны», «Bart to the Future», было упомянуто, что после его президентства в бюджете страны осталась большая дыра. Поэтому с 2015 года о серии вспоминали многие СМИ. После президентских выборов в США-2016, в которых победил Дональд Трамп, создатели «Симпсонов» выразили сожаление, что их предсказание о победе Трампа сбылось и даже извинились за это.

В 2003 году Трамп стал исполнительным продюсером и ведущим реалити-шоу «Кандидат» на канале «Эн-би-си». Это шоу по сути было игрой, в которой участники боролись за право получить должность топ-менеджера в одной из компаний Трампа, а те, кто не проходил испытаний, были «уволены», то есть выбывали из игры. В 2004 году Дональд Трамп подал заявку на регистрацию торговой марки — популярной фразы «Вы уволены!» — «You’re fired!». В первый год показа шоу Трампу платили по $50 тысяч за серию (приблизительно $700 тысяч за первый сезон), а начиная со второго сезона — уже по $3 млн за серию, что сделало его одним из самых высокооплачиваемых людей на телевидении. 

В декабре 2006 года ведущая ток-шоу «The View» Рози О’Доннелл подвергла Трампа критике за то, что он называет себя «моральным компасом для 20-летних» после того, как дал второй шанс мисс США Таре Коннер, которая, несмотря на правила, посещала ночные заведения и позволяла себе пить без меры. Трамп, которому принадлежат права на конкурс, позволил Коннер сохранить корону «Мисс США», пока она проходила курс реабилитации. Таблоидная война между этими знаменитостями сохранялась на протяжении нескольких недель.

В 2007 году Трамп получил звезду на голливудской «Аллее славы» за своё участие в телесериале «Кандидат».

В октябре 2007 года Трамп участвовал в ток-шоу «Ларри Кинг в прямом эфире», где подверг резкой критике действия президента США Джорджа Буша, особенно за участие в Иракской войне. Он также предсказал, что Рудольф Джулиани и Хиллари Клинтон будут претендовать на пост президента от республиканцев и демократов соответственно и он будет рад поддержать каждого из них в предвыборной гонкe. Также свою позицию относительно Ирака Трамп в новостной передаче «The Situation Room» выразил следующими словами: «Я чувствую, что тот, кто хочет ещё больше трупов в Ираке, не сможет победить на выборах президента», намекая на речи Рудольфа Джулиани в поддержку войны в Ираке. На ток-шоу Ларри Кинга Трамп также негативно отозвался по поводу признания Анджелины Джоли первой красавицей мира.

17 сентября 2008 года в ток-шоу «Ларри Кинг в прямом эфире» Трамп официально рекомендовал голосовать за Джона Маккейна на предстоящих выборах президента США
