### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Denys-Shapovalenko** [Denys-Shapovalenko/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by whaplzzz** [comment]
Предприниматель (главным образом в сфере недвижимости), шоумен и телеведущий. Человек года по версии журнала «Time» (2016). С 1971 по 2017 год Дональд Трамп являлся президентом строительного конгломерата Trump Organization и основателем компании Trump Entertainment Resorts, специализирующейся на игорном и гостиничном бизнесе. В 1996—2015 годах был владельцем конкурса красоты «Мисс Вселенная». Появлялся в роли камео в ряде кинофильмов и телесериалов. Кроме того, Дональд Трамп являлся исполнительным продюсером и на протяжении 14 сезонов (2004—2015 годы) был ведущим реалити-шоу «Кандидат» на телеканале «NBC». С президентских выборов 1988 года Дональд Трамп рассматривался как потенциальный кандидат на пост президента США почти на каждых выборах. В октябре 1999 года объявил себя потенциальным кандидатом от Партии реформ, на выдвижение в президенты США[18], но 14 февраля 2000 года снял свою кандидатуру с выборов. Объявил о вступлении в борьбу за пост следующего президента США 16 июня 2015 года. В мае 2016 года, опередив всех соперников на праймериз, фактически гарантировал себе выдвижение единым кандидатом от Республиканской партии. Официально утверждён на партийном съезде, состоявшемся 18—21 июля того же года. Стал вторым в истории кандидатом на пост президента США от двух главных партий, кто был изначально известен прежде всего как бизнесмен и не занимал никаких государственных постов (первым был Уэнделл Уилки в 1940 году) и первым таким кандидатом, выигравшим выборы.

**Comment by Denys-Shapovalenko** [comment]
Excellent
