### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Denys-Shapovalenko** [Denys-Shapovalenko/homepage#8]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by whaplzzz** [comment]
Twitter - https://twitter.com/realdonaldtrump
Личный сайт - https://www.donaldjtrump.com/
Сайт белого дома - https://www.whitehouse.gov/people/donald-j-trump/
