### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Denys-Shapovalenko** [Denys-Shapovalenko/homepage#9]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by whaplzzz** [comment]
До́нальд Джон Трамп (англ. Donald John Trump; род. 14 июня 1946 года, Джамейка, Куинс, Нью-Йорк, США) — американский государственный деятель, политик, предприниматель, президент США с 20 января 2017 года. В конце декабря 2019 года британская газета Financial Times включила Трампа в опубликованный ей список из 50 человек, «определивших облик десятилетия».

**Comment by Denys-Shapovalenko** [comment]
Thnx
